from sqlalchemy import create_engine
import duckdb
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.engine import URL


# --- FORMAL EMAIL TEMPLATES ---
SUCCESS_EMAIL_HTML = """
<div style="font-family: Arial, sans-serif; color: #333; max-width: 650px; margin: auto; border: 1px solid #ddd; padding: 25px; border-radius: 8px;">
    {% set prod_report = ti.xcom_pull(task_ids='produce_to_kafka') %}
    <h2 style="color: #2E86C1; border-bottom: 2px solid #2E86C1; padding-bottom: 10px;">✅ Pipeline Execution Report</h2>
    <p>Dear Data Team,</p>
    <p>The <b>Chocolate Factory Ingestion Pipeline</b> has successfully completed its scheduled run.</p>
    
    <div style="background-color: #f4f6f7; padding: 10px 15px; border-left: 4px solid #2E86C1; margin-bottom: 25px;">
        <p style="margin: 0; font-size: 14px;"><b>Execution Date:</b> {{ data_interval_end.strftime('%A, %B %d, %Y') }}</p>
        <p style="margin: 0; font-size: 14px;"><b>Time:</b> {{ data_interval_end.strftime('%I:%M %p UTC') }}</p>
        <p style="margin: 0; font-size: 14px; margin-top: 5px;"><b>Batch ID:</b> <span style="font-family: monospace;">{{ run_id }}</span></p>
        <p style="margin: 0; font-size: 15px; margin-top: 5px; color: #2E86C1;"><b>Data Period Produced:</b> <span style="font-family: monospace; font-weight: bold;">{{ prod_report.period if prod_report else 'Unknown' }}</span></p>
    </div>
    
    <h3 style="color: #555;">1. Producer Summary (Source to Kafka)</h3>
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 14px;">
        <thead>
            <tr style="background-color: #e9ecef; color: #333;">
                <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Topic Produced</th>
                <th style="border: 1px solid #ddd; padding: 10px; text-align: right;">Amount Produced</th>
            </tr>
        </thead>
        <tbody>
            {% if prod_report and prod_report.counts %}
                {% for topic, count in prod_report.counts.items() %}
                <tr>
                    <td style="border: 1px solid #ddd; padding: 10px;">{{ topic }}</td>
                    <td style="border: 1px solid #ddd; padding: 10px; text-align: right; font-family: monospace;">{{ "{:,}".format(count) }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="2" style="border: 1px solid #ddd; padding: 10px; text-align: center;">No topics produced.</td>
                </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr style="background-color: #f8f9fa;">
                <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Total New Records</th>
                <th style="border: 1px solid #ddd; padding: 10px; text-align: right; font-size: 16px; color: #2E86C1;">
                    {{ "{:,}".format(prod_report.total_new_records) if prod_report else 0 }}
                </th>
            </tr>
        </tfoot>
    </table>

    <h3 style="color: #555;">2. Consumer Summary (Kafka to DuckDB)</h3>
    <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <thead>
            <tr style="background-color: #2E86C1; color: white;">
                <th style="border: 1px solid #ddd; padding: 10px; text-align: left;">Topic Consumed</th>
                <th style="border: 1px solid #ddd; padding: 10px; text-align: right;">Records Loaded to Database</th>
            </tr>
        </thead>
        <tbody>
            {% set consumer_report = ti.xcom_pull(task_ids='consume_to_duckdb') %}
            {% if consumer_report %}
                {% for topic, count in consumer_report.items() %}
                <tr>
                    <td style="border: 1px solid #ddd; padding: 10px;">{{ topic }}</td>
                    <td style="border: 1px solid #ddd; padding: 10px; text-align: right; font-family: monospace;">{{ "{:,}".format(count) }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="2" style="border: 1px solid #ddd; padding: 10px; text-align: center; color: #e74c3c;">
                        <b>Consumer data unavailable.</b> Check if consume_to_duckdb is returning its dictionary.
                    </td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    
    <p style="margin-top: 30px; font-size: 12px; color: #777; border-top: 1px solid #eee; padding-top: 10px;">
        <i>This is an automated system message generated by Apache Airflow. Please do not reply directly to this email.</i>
    </p>
</div>
"""

WARNING_EMAIL_HTML = """
<div style="font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: auto; border: 1px solid #ddd; padding: 20px; border-radius: 8px;">
    {% set prod_report = ti.xcom_pull(task_ids='produce_to_kafka') %}
    <h2 style="color: #D68910; border-bottom: 2px solid #D68910; padding-bottom: 10px;">⚠️ Pipeline Warning: No Data</h2>
    <p>Dear Data Team,</p>
    <p>The <b>Chocolate Factory Ingestion Pipeline</b> ran successfully, but no new records were detected in the source files.</p>
    
    <div style="background-color: #fcf3cf; padding: 10px 15px; border-left: 4px solid #D68910; margin-bottom: 25px;">
        <p style="margin: 0; font-size: 14px;"><b>Execution Date:</b> {{ data_interval_end.strftime('%A, %B %d, %Y') }}</p>
        <p style="margin: 0; font-size: 14px;"><b>Time:</b> {{ data_interval_end.strftime('%I:%M %p UTC') }}</p>
        <p style="margin: 0; font-size: 14px; margin-top: 5px;"><b>Batch ID:</b> <span style="font-family: monospace;">{{ run_id }}</span></p>
        <p style="margin: 0; font-size: 15px; margin-top: 5px; color: #D68910;"><b>Attempted Data Period:</b> <span style="font-family: monospace; font-weight: bold;">{{ prod_report.period if prod_report else 'Unknown' }}</span></p>
        <p style="margin: 0; font-size: 13px; margin-top: 5px;"><b>Status Flag:</b> <i>{{ prod_report.status if prod_report else 'N/A' }}</i></p>
    </div>
    
    <p><b>Outcome:</b> Skipped Consumer Phase. No changes were made to the DuckDB Bronze Layer.</p>
    <p style="margin-top: 30px; font-size: 12px; color: #777;"><i>Automated system message generated by Apache Airflow.</i></p>
</div>
"""

def decide_next_step(**context):
    ti = context['ti']
    report = ti.xcom_pull(task_ids='produce_to_kafka')
    
    if report and report.get('total_new_records', 0) > 0:
        return 'consume_to_duckdb'
    else:
        return 'send_warning_email'
    
        print("Transfer process finished.")


def transfer_duckdb_to_postgres():
    duckdb_path = '/usr/local/airflow/include/STG/chocolate_warehouse.duckdb'
    
    connection_url = URL.create(
        drivername="postgresql+psycopg2",
        username="dwh_user",
        password="dwh_password",  
        host="host.docker.internal",
        port=5434,                # <--- The new port!
        database="dwh"
    )

    target_tables = [
        'stg_fact_sales', 
        'stg_dim_customers', 
        'stg_dim_stores', 
        'stg_dim_products',
        'stg_dim_locations'
    ]
    
    # ==========================================
    # ✅ 1. NEW: Initialize the grand total counter
    # ==========================================
    total_rows_transferred = 0  
    
    try:
        # ✅ Test connection first before touching DuckDB
        pg_engine = create_engine(connection_url)
        with pg_engine.connect() as test_conn:
            print("✅ PostgreSQL connection successful!")

        duck_conn = duckdb.connect(duckdb_path, read_only=True)  # ← read only, safer
        
        for table in target_tables:
            print(f"📖 Reading {table} from DuckDB...")
            df = duck_conn.execute(f"SELECT * FROM {table}").df()
            
            row_count = len(df)  # Store the length so we can use it multiple times
            print(f"   → {row_count} rows found")
            
            df.to_sql(
                table,
                pg_engine,
                if_exists='replace',
                index=False,
                schema='public'
            )
            print(f"✅ {table} → PostgreSQL ({row_count} rows)")
            
            # ==========================================
            # ✅ 2. NEW: Add this table's rows to the total
            # ==========================================
            total_rows_transferred += row_count  
            
        # ==========================================
        # ✅ 3. NEW: Return the total so Airflow catches it
        # ==========================================
        return total_rows_transferred  
            
    except Exception as e:
        print(f"❌ Transfer failed: {e}")
        raise                   # ← fail the task properly
    finally:
        # The finally block will still safely close connections 
        # BEFORE the return value is actually sent back to Airflow!
        if 'duck_conn' in locals():
            duck_conn.close()
        if 'pg_engine' in locals():
            pg_engine.dispose()
        print("🏁 Transfer process finished.")




# ==========================================
# 1. DUCKDB TRUNCATION FUNCTION
# ==========================================
def truncate_duckdb_staging(duckdb_path):
    """Connects to DuckDB and truncates all base tables except raw_locations."""
    print(f"Connecting to DuckDB at: {duckdb_path}")
    import duckdb # Ensure duckdb is imported if not globally available
    conn = duckdb.connect(duckdb_path)
    
    # Dynamically find all tables in the database
    tables = conn.execute("SELECT table_name FROM information_schema.tables WHERE table_type='BASE TABLE'").fetchall()
    
    for table in tables:
        table_name = table[0]
        
        # Check if the table is the one we want to protect
        if table_name == 'raw_locations':
            print(f"⏭️  Skipping truncation for protected table: {table_name}")
            continue # This jumps to the next table in the loop
            
        print(f"🧹 Truncating table: {table_name}")
        conn.execute(f"TRUNCATE TABLE {table_name}")
        
    print("All target DuckDB staging tables truncated successfully.")
    conn.close()